### ISSUE TITLE
wave.Error: unknown format: 3

### ISSUE THREAD

**Issue by Heath123** [hamiltron/py-simple-audio#48]
Trying to play this file:
https://unknown-format-bug-report.heathmitchell1.repl.co/right-attach.wav
causes this error:
```
Traceback (most recent call last):
  File "/home/heath/PycharmProjects/switch-test-3/main.py", line 96, in onQApplicationStarted
    wave_obj = sa.WaveObject.from_wave_file("sounds/right-attach.wav")
  File "/home/heath/PycharmProjects/switch-test-3/venv/lib/python3.8/site-packages/simpleaudio/shiny.py", line 24, in from_wave_file
    wave_read = wave.open(wave_file, 'rb')
  File "/usr/lib/python3.8/wave.py", line 510, in open
    return Wave_read(f)
  File "/usr/lib/python3.8/wave.py", line 164, in __init__
    self.initfp(f)
  File "/usr/lib/python3.8/wave.py", line 144, in initfp
    self._read_fmt_chunk(chunk)
  File "/usr/lib/python3.8/wave.py", line 269, in _read_fmt_chunk
    raise Error('unknown format: %r' % (wFormatTag,))
wave.Error: unknown format: 3

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by Heath123** [comment]
This happens when exporting in Audacity as "32-bit float PCM"
